name: Refresh README

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Organize Files and Update README
        run: python generate_readme.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update README and Organize Files" && git push)

